[project]
name = "srt-to-premiere"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "ctranslate2>=4.8.1",
    "faster-whisper>=1.2.1",
    "huggingface-hub>=1.25.1",
    "nvidia-cublas-cu12>=12.9.2.10 ; sys_platform == 'win32'",
    "nvidia-cudnn-cu12>=9.24.0.43 ; sys_platform == 'win32'",
    "tqdm>=4.70.0",
]
